config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users, controllers: { registrations: "registrations"}

resources "forms"

  

  root 'welcome#index'

end

app/models/form.rb
class Form < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
	before_action :authenticate_user!

	def index
		@forms = Form.all
	end

	def show
	  @form = Form.find(params["id"])
	end

def create
	form_params = params["form"].permit("name", "wins", "repass", "emoji")
  @form = Form.create(form_params)
  @form.user_id = current_user.id
  redirect_to(form_path(@form))
end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }

  end

  def sign_up_params

    params.require(:user).permit(:username, :email, :password, :password_confirmation)

  end

  def account_update_params

    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)

  end

  def after_update_path_for(resource)

    root_path

  end

  def after_sign_up_path_for(resource)

    root_path

  end

  def after_sign_in_path_for(resource)

    stored_location_for(resource) || root_path

  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	 @forms = Form.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/forms/index.html.erb
<h1 class='logo_welcome'>Stand Up</h1>
	
	<p class='line'>______________________________________________________________________</p>
<% for form in @forms %>
	<p class='name'><%= form.name %></p>
	<p class='subtitles'>Wins</p>
	<p><%= form.wins %></p>
	<p class='subtitles'>Repass</p>
	<p><%= form.repass %></p>
	<p class='line'>______________________________________________</p>
<% end %>

app/views/forms/new.html.erb
<!-- <h1 class='logo_welcome'>Stand Up</h1> -->

<div class='form_spacing'>
	<%= form_for(:form, url: '/forms', :method => 'post') do |form| %>
	  <p><%= form.label("Name") %></p>
	  <p><%= form.text_field("name") %></p>
	  <p><%= form.label("Wins") %></p>
	  <p><%= form.text_area("wins") %></p>
	  <p><%= form.label("Repass") %></p>
	  <p><%= form.text_area("repass") %></p>
	  
	<!-- 	<select>
			<option>😄</option>
			<option>😞</option>
			<option>💤</option>
		</select>  -->
					           
	<p> </p>
	  <p><%= form.submit %></p>

	<% end %>
</div>
<p><%= link_to("Back to all Stand Ups", forms_path) %></p>

app/views/forms/show.html.erb
<p><%= link_to("Back to all Stand Ups", forms_path) %></p>
<p> </p>
<p class='name'><%= @form.name %></p>
<p class='subtitles'>Wins</p>	
  <p><%= @form.wins %></p>
  <p class='subtitles'>Repass</p>
  <p><%= @form.repass %></p>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StandUp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
  <link href='https://fonts.googleapis.com/css?family=Reenie+Beanie' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<ul class="nav">
		<p class="navbar-text pull-right">
		<% if user_signed_in? %>
		  Logged in as <strong><%= current_user.email %></strong>.
		  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %> </p>
	</ul>


<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1 class='logo_welcome'>Stand Up</h1>
<p> </p>
	<button><%= link_to("Share Your Feelings", new_form_path) %></button>





 